image: node:24.9.0

stages:
    - quality

cache:
    paths:
        - node_modules/

quality:
    stage: quality
    script:
        - npm ci
        - npm run quality:check
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH
